### ISSUE TITLE
SoundCloud API - Use in fragment

### ISSUE THREAD

**Issue by Jsaiao** [tvbarthel/Cheerleader#5]
Hello friends, was very beautiful and functional the incredible application idea, I would take a doubt I am new to android studio programming and would like to include your project to my application, but without the choice screen as exists in your example, I would use as a fragment in my apliação only an artist I saw that you can do this, after download the GitHub file compiled for testing but do not think any artist seems to be missing some API KEY authorization could help me? Thank you very much in advance.

**Comment by tbarthel-fr** [comment]
Hi @Jsaiao 

Thanks a lot for your interest in this project!

As you mentionned, you need an API KEY to pass to the Builder : 
https://github.com/tvbarthel/Cheerleader#builder

In order to obtain an API KEY, simply create a Soundcloud developer account here : 
https://developers.soundcloud.com/

Then, in order to build a "working" sample, simply but your API KEY here :
https://github.com/tvbarthel/Cheerleader/blob/master/sample/src/main/res/values/ids.xml

Rebuild your project and you should be able to use the sample (=

I'm so sorry for this late answer, end/begging of the year was quite complicated...

Don't hesitate to request for more help if needed, we're back to business (:

Thomas.
